### PR TITLE
Switch to the new templating module

### PR DESCRIPTION
**Pull request by joewiz**
In preparation for release of eXist 5.3.0 - see eXist-db/exist#3914.

### CODE REVIEW

**Comment by joewiz** [comment]
We may want to pause on merging this PR until https://github.com/eXist-db/exist/issues/3918 is resolved. The `lib:parse-params` templating function is affected by this issue.

**Comment by line-o** [comment]
Shouldn't we also depend on 1.0.2 here?
And even if it is just to not install 1.0.1 by accident.

**Review by line-o — APPROVED** [review]
Oh, I see we already depend on 1.0.2
Then, all is fine

**Comment by joewiz** [comment]
@line-o Thank you!

**Pull request merged**
